#!/usr/bin/env bash

CUR="`pwd`"   # save the current directory, so can change back after startup

if [ "x$CUR" = "x" ]; then
    echo "**************************************************************"
    echo " Error: the current working directory does not exist. Please  "
    echo " run Qsnake again from an existing directory.                 "
    echo "**************************************************************"
    exit 1
fi

QSNAKE_ROOT=`readlink -n "$0" 2> /dev/null` || \
QSNAKE_ROOT=`realpath    "$0" 2> /dev/null` || \
QSNAKE_ROOT="$0"

QSNAKE_ROOT="${QSNAKE_ROOT%/*}/"

# Make root absolute:
cd "$QSNAKE_ROOT"
QSNAKE_ROOT=`pwd`
export QSNAKE_ROOT
export CUR

if [ ! -f "$QSNAKE_ROOT/local/bin/python" ]; then
    PYTHON=
    QSNAKE_SYSTEMWIDE_PYTHON="yes"
else
    PYTHON="$QSNAKE_ROOT/local/bin/python "
    QSNAKE_SYSTEMWIDE_PYTHON="no"
    # this is necessary to reset the PYTHONPATH and other stuff:
    . "$QSNAKE_ROOT/local/bin/qsnake-env"
fi
export QSNAKE_SYSTEMWIDE_PYTHON

$PYTHON"$QSNAKE_ROOT/spkg/base/qsnake_run.py" "$@"
