#! /bin/sh

# Multiplatform wget -nc emulation

if [ -z "$(which wget)" ]; then
    wgetnc() {
        # emulate wget -nc with curl
        fname="$(echo $@ | awk -F / '{ print $NF }')"
        if [ -f "$fname" ]; then
            echo "File '$fname' already there; not retrieving."
        else
            # Curl doesn't print the downloaded file by default
            echo "Downloading $@"
            curl -O $@
        fi
        echo
    }
    WGET="wgetnc"
else
    WGET="wget -nc"
fi

$WGET $@
