#! /bin/sh

# Multiplatform wget emulation

if [ `uname` = 'Darwin' ]; then
    # Curl doesn't print the downloaded file by default
    echo "Downloading $@"
    WGET="curl -O"
else
    WGET="wget -nc"
fi

$WGET $@
