#!/usr/bin/env bash

if [ "$QSNAKE_ROOT" = "" ]; then
    echo "QSNAKE_ROOT must be set"
    exit 1
fi

# Setting project neutral envrironment variables
export SPKG_LOCAL="$QSNAKE_ROOT/local"
export PATH="$QSNAKE_ROOT:$SPKG_LOCAL/bin:$PATH"
export LIBRARY_PATH="$SPKG_LOCAL/lib/:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$SPKG_LOCAL/lib/:$LD_LIBRARY_PATH"
export PYTHONPATH="$SPKG_LOCAL/lib/python"
export PYTHONHOME="$SPKG_LOCAL"


# Setting Sage-related location environment variables.
export SAGE_ROOT="$QSNAKE_ROOT"
export SAGE_PACKAGES="$QSNAKE_ROOT/spkg"
export SAGE_LOCAL="$SPKG_LOCAL"
export SAGE_DATA="$QSNAKE_ROOT/data"
export SAGE_DOC="$QSNAKE_ROOT/devel/sage/doc"

if [ "$DOT_SAGE" = "" ]; then
    export DOT_SAGE="$HOME/.qsnake/"
fi

if [ "$SAGE_STARTUP_FILE" = "" ]; then
    export SAGE_STARTUP_FILE="$DOT_SAGE/init.sage"
fi

############ compilation flags

# Set the default compiler to gcc if the enviroment variable
# CC is not set.
if [ "$CC" = "" ]; then
     export CC="gcc"
fi

 # Set the default C++ compiler to g++ if the environment variable
# CXX is not set.
if [ "$CXX" = "" ]; then
    export CXX="g++"
fi

if [ "$LD" = "" ]; then
    export LD="ld"
fi
if [ "$AR" = "" ]; then
    export AR="ar"
fi
if [ "$AS" = "" ]; then
    export AS="as"
fi

UNAME=`uname`
if [ `uname | sed -e 's/WIN.\+/WIN/'` = "CYGWIN" ]; then
    UNAME="CYGWIN"
fi
export UNAME

if [ "$LDFLAGS" = "" ]; then
    export LDFLAGS=""
fi

if [ "$CXXFLAGS" = "" ]; then
   export CXXFLAGS="$CFLAGS"
fi

if [ "$CP" = "" ]; then
    export CP="cp"
fi

if [ "$MV" = "" ]; then
    export MV="mv"
fi

if [ "$MAKE" = "" ]; then
    export MAKE="make"
fi

if [ "$RM" = "" ]; then
    export RM="rm"
fi

if [ "$RANLIB" = "" ]; then
    export RANLIB="ranlib"
fi

if [ "$LN" = "" ]; then
    export LN="ln"
fi

if [ "$MKDIR" = "" ]; then
    export MKDIR="mkdir"
fi

if [ "$CHMOD" = "" ]; then
    export CHMOD="chmod"
fi

if [ "$TOUCH" = "" ]; then
    export TOUCH="touch"
fi

if [ "$MAKEFLAGS" != "" ]; then
    export MFLAGS="$MAKEFLAGS"
fi
